version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # see https://github.com/jenkinsci/jenkins/pull/5112#issuecomment-744429487 and https://github.com/jenkinsci/jenkins/pull/5116#issuecomment-744526638
      # it would be good to update it at some point, but requires significant testing
      - dependency-name: "org.codehaus.groovy:groovy-all"
      # see https://github.com/jenkinsci/jenkins/pull/5184 should be updated with groovy-all
      - dependency-name: "org.fusesource.jansi:jansi"
      # see https://github.com/jenkinsci/jenkins/pull/4328 and https://github.com/jenkinsci/jenkins/pull/4928#issuecomment-730224123
      # fix requires investigation, for now we don't want dependabot updating it
      - dependency-name: "commons-beanutils:commons-beanutils"
      # see https://github.com/jenkinsci/jenkins/pull/5144#pullrequestreview-559661934
      # will require source code changes to replace javax.mail with jakarta.mail 
      # and some handling for plugins that depend on javax.mail being provided by Jenkins core.
      - dependency-name: "com.sun.mail:jakarta.mail"
      # needs updates in a number of plugins, see https://github.com/jenkinsci/jenkins/pull/5059 and https://github.com/jenkinsci/bom/pull/392
      - dependency-name: "com.google.guava:*"
      # this is a banned dependency, we have a hack in our pom to prevent anyone else pulling it in
      - dependency-name: "javax.servlet.servlet-api"
      # needs a jakarta upgrade project, imports changed
      - dependency-name: "jakarta.servlet.jsp.jstl.jakarta.servlet.jsp.jstl-api"
      # see https://github.com/jenkinsci/jenkins/pull/4224 can't be updated without breaking api
      - dependency-name: "org.jfree:jfreechart"
