version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # see https://github.com/jenkinsci/jenkins/pull/5112#issuecomment-744429487 and https://github.com/jenkinsci/jenkins/pull/5116#issuecomment-744526638
      # it would be good to update it at some point, but requires significant testing
      - dependency-name: "org.codehaus.groovy:groovy-all"
      # see https://github.com/jenkinsci/jenkins/pull/4328 and https://github.com/jenkinsci/jenkins/pull/4928#issuecomment-730224123
      # fix requires investigation, for now we don't want dependabot updating it
      - dependency-name: "commons-beanutils:commons-beanutils"
